# Generated by Django 4.1.10 on 2023-09-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainlink_fro', '0004_logininstructor_loginstudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
