# Generated by Django 4.1.10 on 2023-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainlink_fro', '0006_loginadministrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(max_length=11),
        ),
    ]
