# Generated by Django 4.1.10 on 2023-09-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brainlink_fro', '0007_alter_course_course_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignmentsub',
            field=models.CharField(default='', max_length=100),
        ),
    ]
